#!/bin/bash

BMC_IP="192.168.1.100"
USER="root"
PASS="0penBmc"

echo "===== IPMI HEALTH CHECK ====="
echo "BMC: $BMC_IP"
echo "-----------------------------"

# Power status
echo "[+] Power Status:"
ipmitool -I lanplus -H $BMC_IP -U $USER -P $PASS power status

echo ""

# Sensor data (temp & fan only)
echo "[+] Sensors (Temp & Fan):"
ipmitool -I lanplus -H $BMC_IP -U $USER -P $PASS sdr list | grep -i -E "temp|fan"

echo ""

# Last 5 system events
echo "[+] Recent Events:"
ipmitool -I lanplus -H $BMC_IP -U $USER -P $PASS sel list | tail -5

echo "-----------------------------"
echo "[+] Done"





#RESULTS
#===== IPMI HEALTH CHECK =====
#BMC: 192.168.1.100
#-----------------------------
#[+] Power Status:
#Chassis Power is on

#[+] Sensors (Temp & Fan):
#CPU1 Temp      | 42 degrees C | ok
#CPU2 Temp      | 45 degrees C | ok
#Fan1           | 12000 RPM    | ok

#[+] Recent Events:
#No entries
#-----------------------------
#[+] Done
